language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

sudo: false

before_install:
  - composer self-update
  - composer clear-cache
  - composer update

script:
  ./vendor/bin/phpunit